package raftstore

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"hash/crc32"

	"github.com/andrew01234567890/vbdb/internal/coordinates"
	"github.com/andrew01234567890/vbdb/internal/storage"
	"github.com/andrew01234567890/vbdb/pkg/jsondoc"
	"github.com/andrew01234567890/vbdb/pkg/uuidv7"
)

const (
	commandMagic       = "VBCM"
	commandFormat      = byte(1)
	commandPut         = byte(1)
	maxCommandTable    = coordinates.MaxTableBytes
	maxCommandKey      = coordinates.MaxKeyBytes
	maxCommandValue    = 1 << 20
	commandHeaderBytes = 4 + 1 + 1 + 16 + 16 + 2 + 2 + 4 + 1
)

var commandCRC = crc32.MakeTable(crc32.Castagnoli)

var (
	ErrInvalidCommand     = errors.New("raftstore: invalid command")
	ErrInvalidOperationID = errors.New("raftstore: invalid operation id")
	ErrOperationConflict  = errors.New("raftstore: operation id is already bound to another command")
	ErrBackpressure       = errors.New("raftstore: proposal backpressure")
	ErrCorrupt            = errors.New("raftstore: corrupt persisted data")
)

// Command is the deterministic state-machine input for a shard. Version is
// generated by the client before proposal; replicas never generate it while
// applying a committed entry.
type Command struct {
	OperationID uuidv7.UUID
	Table       string
	Key         string
	Value       []byte
	Condition   storage.Condition
	Version     uuidv7.UUID
}

// NewPut creates a command with independently generated operation and row
// UUIDv7 values. A caller retrying a proposal must retain and reuse it.
func NewPut(table, key string, value []byte, condition storage.Condition, generate func() (uuidv7.UUID, error)) (Command, error) {
	if generate == nil {
		generate = uuidv7.New
	}
	op, err := generate()
	if err != nil {
		return Command{}, fmt.Errorf("raftstore: generate operation id: %w", err)
	}
	version, err := generate()
	if err != nil {
		return Command{}, fmt.Errorf("raftstore: generate row version: %w", err)
	}
	command := Command{OperationID: op, Table: table, Key: key, Value: append([]byte(nil), value...), Condition: condition, Version: version}
	if err := validateCommand(command); err != nil {
		return Command{}, err
	}
	return command, nil
}

func validateCommand(command Command) error {
	if _, err := uuidv7.UUIDFromBytes(command.OperationID[:]); err != nil {
		return fmt.Errorf("%w: operation id: %v", ErrInvalidOperationID, err)
	}
	if _, err := uuidv7.UUIDFromBytes(command.Version[:]); err != nil {
		return fmt.Errorf("%w: row version: %v", ErrInvalidCommand, err)
	}
	if !validTable(command.Table) || !validKey(command.Key) {
		return fmt.Errorf("%w: coordinates", ErrInvalidCommand)
	}
	if err := validateCanonicalValue(command.Value); err != nil {
		return fmt.Errorf("%w: value: %v", ErrInvalidCommand, err)
	}
	if command.Condition.CreateOnly && command.Condition.IfMatch != nil {
		return fmt.Errorf("%w: create-only and if-match cannot be combined", ErrInvalidCommand)
	}
	if command.Condition.IfMatch != nil {
		if _, err := uuidv7.UUIDFromBytes(command.Condition.IfMatch[:]); err != nil {
			return fmt.Errorf("%w: if-match: %v", ErrInvalidCommand, err)
		}
	}
	return nil
}

func validTable(table string) bool {
	return coordinates.ValidTable(table)
}

func validKey(key string) bool {
	return coordinates.ValidKey(key)
}

func validateCanonicalValue(value []byte) error {
	if len(value) > maxCommandValue {
		return errors.New("value too large")
	}
	canonical, err := jsondoc.Canonicalize(value)
	if err != nil {
		return fmt.Errorf("not valid JSON: %v", err)
	}
	if len(canonical) > maxCommandValue {
		return errors.New("canonical value too large")
	}
	if !bytes.Equal(canonical, value) {
		return errors.New("value is not canonical JSON")
	}
	return nil
}

// EncodeCommand returns a canonical, versioned, checksummed command. The
// fixed-width UUIDs and big-endian lengths make encoding independent of Go
// implementation details and map iteration order.
func EncodeCommand(command Command) ([]byte, error) {
	if err := validateCommand(command); err != nil {
		return nil, err
	}
	flags := byte(0)
	if command.Condition.CreateOnly {
		flags |= 1
	}
	if command.Condition.IfMatch != nil {
		flags |= 2
	}
	encoded := make([]byte, 0, commandHeaderBytes+len(command.Table)+len(command.Key)+len(command.Value)+16+4)
	encoded = append(encoded, commandMagic...)
	encoded = append(encoded, commandFormat, commandPut)
	encoded = append(encoded, command.OperationID[:]...)
	encoded = append(encoded, command.Version[:]...)
	var number [4]byte
	binary.BigEndian.PutUint16(number[:2], uint16(len(command.Table)))
	encoded = append(encoded, number[:2]...)
	binary.BigEndian.PutUint16(number[:2], uint16(len(command.Key)))
	encoded = append(encoded, number[:2]...)
	binary.BigEndian.PutUint32(number[:], uint32(len(command.Value)))
	encoded = append(encoded, number[:]...)
	encoded = append(encoded, flags)
	if command.Condition.IfMatch != nil {
		encoded = append(encoded, command.Condition.IfMatch[:]...)
	}
	encoded = append(encoded, command.Table...)
	encoded = append(encoded, command.Key...)
	encoded = append(encoded, command.Value...)
	var checksum [4]byte
	binary.BigEndian.PutUint32(checksum[:], crc32.Checksum(encoded, commandCRC))
	return append(encoded, checksum[:]...), nil
}

// DecodeCommand validates and decodes only the canonical command format.
func DecodeCommand(encoded []byte) (Command, error) {
	if len(encoded) < commandHeaderBytes+4 || !bytes.Equal(encoded[:4], []byte(commandMagic)) || encoded[4] != commandFormat || encoded[5] != commandPut {
		return Command{}, fmt.Errorf("%w: header", ErrInvalidCommand)
	}
	if len(encoded) < 4 || crc32.Checksum(encoded[:len(encoded)-4], commandCRC) != binary.BigEndian.Uint32(encoded[len(encoded)-4:]) {
		return Command{}, fmt.Errorf("%w: checksum", ErrInvalidCommand)
	}
	var command Command
	copy(command.OperationID[:], encoded[6:22])
	copy(command.Version[:], encoded[22:38])
	tableLen := int(binary.BigEndian.Uint16(encoded[38:40]))
	keyLen := int(binary.BigEndian.Uint16(encoded[40:42]))
	valueLen := int(binary.BigEndian.Uint32(encoded[42:46]))
	flags := encoded[46]
	if flags&^byte(3) != 0 || (flags&1 != 0 && flags&2 != 0) {
		return Command{}, fmt.Errorf("%w: flags", ErrInvalidCommand)
	}
	if tableLen == 0 || tableLen > maxCommandTable || keyLen == 0 || keyLen > maxCommandKey || valueLen > maxCommandValue {
		return Command{}, fmt.Errorf("%w: lengths", ErrInvalidCommand)
	}
	position := commandHeaderBytes
	if flags&2 != 0 {
		if len(encoded) < position+16 {
			return Command{}, fmt.Errorf("%w: if-match length", ErrInvalidCommand)
		}
		version := new(uuidv7.UUID)
		copy(version[:], encoded[position:position+16])
		command.Condition.IfMatch = version
		position += 16
	}
	if len(encoded) != position+tableLen+keyLen+valueLen+4 {
		return Command{}, fmt.Errorf("%w: payload length", ErrInvalidCommand)
	}
	command.Table = string(encoded[position : position+tableLen])
	position += tableLen
	command.Key = string(encoded[position : position+keyLen])
	position += keyLen
	command.Value = append([]byte(nil), encoded[position:position+valueLen]...)
	command.Condition.CreateOnly = flags&1 != 0
	if err := validateCommand(command); err != nil {
		return Command{}, err
	}
	canonical, err := EncodeCommand(command)
	if err != nil || !bytes.Equal(canonical, encoded) {
		return Command{}, fmt.Errorf("%w: non-canonical encoding", ErrInvalidCommand)
	}
	return command, nil
}
